const CounterTypes = {
  INCREASE_COUNT: "INCREASE_COUNT",
  INCREASE_PER_SECOND: "INCREASE_PER_SECOND",
  RESET_PROGRESS: "RESET_PROGRESS",
  GRANDMA_BOUGHT: "GRANDMA_BOUGHT",
  FARM_BOUGHT: "FARM_BOUGHT",
  MINE_BOUGHT: "MINE_BOUGHT",
  FACTORY_BOUGHT: "FACTORY_BOUGHT",
  CITY_BOUGHT: "CITY_BOUGHT",
  COUNTRY_BOUGHT: "COUNTRY_BOUGHT",
  INCREASE_BY_BOTS: "INCREASE_BY_BOTS"
};
export default {
  ...CounterTypes
};
