const ShopTypes = {
  GRANDMA_INCREASE: "GRANDMA_INCREASE",
  FARM_INCREASE: "FARM_INCREASE",
  MINE_INCREASE: "MINE_INCREASE",
  FACTORY_INCREASE: "FACTORY_INCREASE",
  CITY_INCREASE: "CITY_INCREASE",
  COUNTRY_INCREASE: "COUNTRY_INCREASE",
  GRANDMA_RESET: "GRANDMA_RESET",
  FARM_RESET: "FARM_RESET",
  MINE_RESET: "MINE_RESET",
  FACTORY_RESET: "FACTORY_RESET",
  CITY_RESET: "CITY_RESET",
  COUNTRY_RESET: "COUNTRY_RESET"
};
export default {
  ...ShopTypes
};
