const ShopTypes = {
  GRANDMA_INCREASE: "GRANDMA_INCREASE",
  FARM_INCREASE: "FARM_INCREASE",
  MINE_INCREASE: "MINE_INCREASE",
  FACTORY_INCREASE: "FACTORY_INCREASE",
  CITY_INCREASE: "CITY_INCREASE",
  COUNTRY_INCREASE: "COUNTRY_INCREASE"
};
export default {
  ...ShopTypes
};
